food_platform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: food_user
      password: food_password123
      dbname: food_platform
      schema: staging
      threads: 1